speak:
  name: Speak (queued)
  description: Enqueue a TTS message for serialized playback.
  fields:
    message:
      required: true
      selector:
        text:
    proxy_id:
      required: false
      selector:
        text:
    media_player_entity_id:
      required: false
      selector:
        entity:
          domain: media_player
    language:
      required: false
      selector:
        text:
    options:
      required: false
      selector:
        object:
    interrupt:
      required: false
      default: false
      selector:
        boolean:
    priority:
      required: false
      default: 0
      selector:
        number:
          min: -10
          max: 10
          step: 1
    volume_override:
      required: false
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
    pre_roll_ms:
      required: false
      selector:
        number:
          min: 0
          max: 1000
          step: 10