"""Constants for Que Cast."""

DOMAIN = "que_cast"

CONF_NAME = "name"
CONF_MEDIA_PLAYER = "media_player"
CONF_TTS_ENGINE = "tts_engine"
CONF_DEFAULT_LANGUAGE = "default_language"
CONF_DEFAULT_OPTIONS = "default_options"
CONF_DAY_VOLUME = "day_volume"
CONF_NIGHT_VOLUME = "night_volume"
CONF_QUIET_START = "quiet_start"
CONF_QUIET_END = "quiet_end"
CONF_PRE_ROLL_SOUND = "pre_roll_sound"
CONF_PRE_ROLL_MS = "pre_roll_ms"
CONF_POST_GRACE_MS = "post_grace_ms"
CONF_DUCKING_ENABLED = "ducking_enabled"
CONF_DETECTION_MODE = "detection_mode"
