que_cast.speak:
  description: Queue a TTS message through Que Cast.
  fields:
    instance_id:
      description: The Que Cast instance ID.
      example: "living_room"
      required: true
      selector:
        text:
    message:
      description: The text to speak.
      example: "Hello from Que Cast!"
      required: true
      selector:
        text:
    language:
      description: Language code for TTS.
      example: "en-US"
      required: false
      selector:
        text:
    options:
      description: JSON options for TTS engine.
      example: '{"voice": "en-US-Wavenet-D"}'
      required: false
      selector:
        text:
    interrupt:
      description: Interrupt current playback.
      example: true
      default: false
      required: false
      selector:
        boolean:
    priority:
      description: Message priority (higher = sooner).
      example: 1
      default: 0
      required: false
      selector:
        number:
          min: -10
          max: 10
          step: 1
    volume_override:
      description: Override volume for this message.
      example: 0.7
      required: false
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.1
    pre_roll_ms:
      description: Pre-roll delay in ms.
      example: 150
      required: false
      selector:
        number:
          min: 0
          max: 1000
          step: 10

que_cast.clear_queue:
  description: Clear the queue for a Que Cast instance.
  fields:
    instance_id:
      description: The Que Cast instance ID.
      example: "living_room"
      required: true
      selector:
        text:

que_cast.skip_current:
  description: Skip the current playing message.
  fields:
    instance_id:
      description: The Que Cast instance ID.
      example: "living_room"
      required: true
      selector:
        text:
